name: Extension CI

on:
  workflow_dispatch: # allows us to trigger our workflow manually
  push:
    branches: [master, main] # triggers workflow on code push to master/main branch
    paths:
      - 'manifest.json' # triggers workflow only if manifest.json is changed
      
jobs:
  Chrome:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Pack extension
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: ./pip-everywhere.crx
        exclusions: '.git/* .vscode/* .github/* *.md'
        
    - name: Publish Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: New Release
