name: Extension CI

on:
  workflow_dispatch: # allows us to trigger our workflow manually
  push:
    tags:
    - '*'
      
jobs:
  Chrome:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Pack extension
      uses: TheDoctor0/zip-release@0.6.2
      with:
        filename: ./pip-everywhere.crx
        exclusions: '.git/* .vscode/* .github/* *.md'
        
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "pip-everywhere.crx"
