name: Extension CI

on:
  workflow_dispatch: # allows us to trigger our workflow manually
  push:
    tags:
    - 'v*'
      
jobs:
  Chrome:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - id: packExtensionDir
      uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
      with:
        extensionDir: 'src'
        zipFilePath: 'build/pip-everywhere.zip'
        
    - name: Sign Chrome Extension crx file
      # You may pin to the exact commit or the version.
      # uses: cardinalby/webext-buildtools-chrome-crx-action@2f388677cdd648cfd9acb27f7d59c695ba0fcf82
      uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.1
      with:
        # Path to WebExtension directory
        zipFilePath: 'build/pip-everywhere.zip'
        # Path to save result crx file
        crxFilePath: 'build/pip-everywhere.crx'
        # Contents of private key used to sign crx file
        privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
        # Path to save update.xml file for extensions hosted not on Chrome Web Store. This xml is used as response at url, specified in manifest's `update_url` key file
        # updateXmlPath: # optional
        # Required, if you specified updateXmlPath. URL to the .crx file
        # updateXmlCodebaseUrl: # optional
        # App Id to use in update.xml file. Generated from private key by default
        # updateXmlAppId: # optional

        
    - name: Action Release
      uses: softprops/action-gh-release@v1
      with:
        files: "build/pip-everywhere.crx"
        
